### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by jzlin1997** [ragavsachdeva/The-Change-You-Want-to-See#1]
when i run the code, it get the error "`return_transform` is deprecated. Please access the transformation matrix with "
ValueError: `return_transform` is deprecated. Please access the transformation matrix with `.transform_matrix`. For chained matrices, please use `AugmentationSequential`"

**Comment by jzlin1997** [comment]
when i set the return_transform == None, the output of self.aff is one, but we want to get two
`input, transformation = self.aff(input)`
the 43 line in aumentation.py

**Comment by ragavsachdeva** [comment]
Hi! could you try installing kornia using:
`pip install kornia @ git+https://github.com/kornia/kornia@77589a58be6c603b7afd755d261783bd0c152a97`
and see if this fixes the issue?
For reference, I have updated [requirements.readme](https://github.com/ragavsachdeva/The-Change-You-Want-to-See/blob/main/requirements.readme) file with the output of `pip freeze` to resolve any dependency issues.

**Comment by ragavsachdeva** [comment]
Hi! could you try installing kornia using:
`pip install kornia@git+https://github.com/kornia/kornia@77589a58be6c603b7afd755d261783bd0c152a97`
and see if this fixes the issue?
For reference, I have updated [requirements.readme](https://github.com/ragavsachdeva/The-Change-You-Want-to-See/blob/main/requirements.readme) file with the output of `pip freeze` to resolve any dependency issues.

**Comment by jzlin1997** [comment]
thanks, previous question  is ok when i pip install kornia@git+https://github.com/kornia/kornia@77589a58be6c603b7afd755d261783bd0c152a97
But, i get the error
`Traceback (most recent call last): `
`File "The-Change-You-Want-to-See/main.py", line 98, in <module>`
`    model = CenterNetWithCoAttention(configs)`
`  File "The-Change-You-Want-to-See/models/centernet_with_coam.py", line 38, in __init__`
`    disable_segmentation_head=True,`
`  File "The-Change-You-Want-to-See/models/unet.py", line 109, in __init__`
`    self.initialize()`
`  File "lib/python3.7/site-packages/segmentation_models_pytorch/base/model.py", line 8, in initialize`
`    init.initialize_head(self.segmentation_head)`
`  File "lib/python3.7/site-packages/segmentation_models_pytorch/base/initialization.py", line 23, in initialize_head`
 `   for m in module.modules():`
`AttributeError: 'NoneType' object has no attribute 'modules'`


when i set disable_segmentation_head=False (38 line in centernet_with_coam.py), i get `_pickle.UnpicklingError: invalid load key, '\x1f'.`
`Traceback (most recent call last):`
`  File "The-Change-You-Want-to-See/main.py", line 130, in <module>`
 `   callbacks,`
 ` File "The-Change-You-Want-to-See/main.py", line 46, in test`
 `   tester.test(model=model, datamodule=datamodule, ckpt_path=checkpoint_path)`
 ` File "lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 862, in test`
 `   return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)`
 ` File "lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt`
 `   return trainer_fn(*args, **kwargs)`
 ` File "lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 909, in _test_impl`
 `   results = self._run(model, ckpt_path=self.ckpt_path)`
 ` File "lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1110, in _run`
 `   self._restore_modules_and_callbacks(ckpt_path)`
 ` File "lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1063, in _restore_modules_and_callbacks`
 `   self._checkpoint_connector.resume_start(checkpoint_path)`
 ` File "lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 85, in resume_start`
 `   self._loaded_checkpoint = self._load_and_validate_checkpoint(checkpoint_path)`
 ` File "lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 89, in _load_and_validate_checkpoint`
`    loaded_checkpoint = self.trainer.strategy.load_checkpoint(checkpoint_path)`
`  File "lib/python3.7/site-packages/pytorch_lightning/strategies/strategy.py", line 339, in load_checkpoint`
`    return self.checkpoint_io.load_checkpoint(checkpoint_path)`
`  File "lib/python3.7/site-packages/pytorch_lightning/plugins/io/torch_plugin.py", line 85, in load_checkpoint`
`    return pl_load(path, map_location=map_location)`
`  File "lib/python3.7/site-packages/pytorch_lightning/utilities/cloud_io.py", line 47, in load`
`    return torch.load(f, map_location=map_location)`
`  File "lib/python3.7/site-packages/torch/serialization.py", line 713, in load`
`    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)`
`  File "lib/python3.7/site-packages/torch/serialization.py", line 920, in _legacy_load`
`    magic_number = pickle_module.load(f, **pickle_load_args)`
`_pickle.UnpicklingError: invalid load key, '\x1f'.`

**Comment by ragavsachdeva** [comment]
Hi! All these issues are dependency based. Can you please look at the _updated_ [requirements.readme](https://github.com/ragavsachdeva/The-Change-You-Want-to-See/blob/main/requirements.readme)? I have added my output of `pip freeze` so that you can compare your installed package versions with what I had in my conda env.

For this specific issue, I think what you need is:
`pip install segmentation-models-pytorch@git+https://github.com/ragavsachdeva/segmentation_models.pytorch.git@dc6009cc57f4d45662c4e838b5daf26663df4f7c`

**Comment by ragavsachdeva** [comment]
FYI, I have since updated the installation guide. Hopefully, it works now with no problems:)
