### ISSUE TITLE
Inpaint Mask id

### ISSUE THREAD

**Issue by wangchust** [ragavsachdeva/The-Change-You-Want-to-See#10]
Hi, thank you for this great work. But how do you define the relation between the mask IDS in the filename of the inpainted image and annotation masks in Inpainted-COCO dataset? I am confused about that.

**Comment by ragavsachdeva** [comment]
Hi, sorry for the delayed response. I am no longer actively monitoring this repo. If I am understanding this correctly, your question is about [this](https://github.com/ragavsachdeva/The-Change-You-Want-to-See/blob/main/data/inpainted_coco_dataset.py#L83), is that right?

Here is a brief explanation (the details may be slightly off, but the idea is sound): From memory, each image has a list of default coco annotations e.g. [obj1, obj2, obj3]. During preprocessing, I randomly inpainted some of these objects which I represent with a binary array e.g. [1, 0, 1] implies obj2 has been inpainted. I then converted this binary array to decimal 101 => 5 ([see](https://www.rapidtables.com/convert/number/binary-to-decimal.html?x=101)). The ID in the filename represents the decimal value. So when I load the annotations, I convert the decimal back to a binary array to figure out which objects were inpainted in the image.

**Comment by wangchust** [comment]
Thanks for your explanation.
