### ISSUE TITLE
Inference scritpt for custom data?

### ISSUE THREAD

**Issue by baishali1986** [ragavsachdeva/The-Change-You-Want-to-See#2]
Hi  Authors

Thanks for releasing the code and the trained checkpoint. I was wondering if you have an inference script to infer on custom pair of images to quickly visualize how  the trained network (which you release in the repo) performs. It will be very helpful if you can provide a small script for that or point me what to use.
B

**Comment by ragavsachdeva** [comment]
Hi! That's a great suggestion.

I added a [demo_single_pair.py](https://github.com/ragavsachdeva/The-Change-You-Want-to-See/blob/main/demo_single_pair.py). You can run it using:
`python demo_single_pair.py --load_weights_from <path_to_checkpoint> --config_file configs/detection_resnet50_3x_coam_layers_affine.yml --decoder_attention scse`

Hope this helps!

As a side note: With the last few commits, I also removed some legacy code so you might need to reclone the repository if you had already downloaded the code and possibly also reinstall the requirements (particularly `segmentation-models-pytorch@git+https://github.com/ragavsachdeva/segmentation_models.pytorch.git@0092ee4d6f851d89a4a401bb2dfa6187660b8dd3`).

Please let me know if you run into any issues. If not, feel free to close this issue:)

**Comment by baishali1986** [comment]
Hi Raghav

Thanks a lot. Let me give it a try :)

**Comment by baishali1986** [comment]
I have package mismatch issue with cuda( i have 11.2  and the requirement is 11.3) which is leading to other package version issues. So I couldnt test the inference script yet.
