### ISSUE TITLE
Questions About the Training Time

### ISSUE THREAD

**Issue by LovingBigMac** [ragavsachdeva/The-Change-You-Want-to-See#3]
Hi author, I really love this work and want to follow it. But I can only access limited machine resources. Can you please provide the training time info on these datasets?

**Comment by ragavsachdeva** [comment]
Hi, here are some estimates from my logs (training on Coco-Inpainted):

- 2x Tesla M40 24GB: ~58mins per epoch
- 2x Tesla P40 24GB: ~54mins per epoch
- 2x Quadro RTX 6000: ~42mins per epoch

Normally, I trained it for 60epochs during prototyping and experimentation. However, for the final model I ran it for longer (200 epochs). So if you have 2x decent GPUs to work with, you can expect the training to take about 2ish days.

**Comment by LovingBigMac** [comment]
The infos help me a lot. Really appreciate that!
