### ISSUE TITLE
Nan Problem

### ISSUE THREAD

**Issue by LovingBigMac** [ragavsachdeva/The-Change-You-Want-to-See#4]
Hello author, I have run the whole pipeline and found that the AP metric shows Nan value while the mAP metric shows normal values. Is this acceptable?

**Comment by ragavsachdeva** [comment]
Hi, it should look something like:

`<test set name> AP: [       nan <value>], mAP: <value>`

and the `<value>` for AP and mAP should be the same.

If you're seeing this, yes it's the expected behaviour (you can safely ignore the `nan`).
