### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by henuJackSon** [ragavsachdeva/The-Change-You-Want-to-See#5]
I have downloaded the pretrained model `pretrained-resnet50-3x-coam-scSE-affine.ckpt`that you uploaded on GitHub and configured the related environment. In this case, `demo_single_pair.py` is located in the same folder as `pretrained-resnet50-3x-coam-scSE-affine.ckpt`.After running the command `python demo_single_pair.py --load_weights_from pretrained-resnet50-3x-coam-scSE-affine.ckpt --config_file configs/detection_resnet50_3x_coam_layers_affine.yml --decoder_attention scse`， the system prompted to download a resnet50-19c8e357.pth file remotely. However, it then displayed an error message: 
`Traceback (most recent call last):`
  `File "demo_single_pair.py", line 117, in <module>`
    `model = CenterNetWithCoAttention(configs)`
  `File "/root/11/The-Change-You-Want-to-See/models/centernet_with_coam.py", line 58, in __init__`
    `self.safely_load_state_dict(torch.load(args.load_weights_from)["state_dict"])`
  `File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 600, in load`
    `with _open_zipfile_reader(opened_file) as opened_zipfile:`
 `File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__`
    `super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))`
`RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`
Could you please provide guidance on how to resolve this issue?
Thank you for your attention.

**Comment by ragavsachdeva** [comment]
Hi, I believe this happens when the file is not downloaded completely (and is therefore corrupted). See: https://stackoverflow.com/a/72085914

Try running `torch.load("pretrained-resnet50-3x-coam-scSE-affine.ckpt")["state_dict"]` in a new python file and see if this works without any errors (and maybe try downloading the checkpoints again?)

**Comment by henuJackSon** [comment]
Hello author, I hope this message finds you well. The pre-trained model has been successfully running, but during the process, the model first loaded and then raised an error:` TypeError: __init__() got an unexpected keyword argument 'return_transform'`. Upon clicking on the K.augmentation.Resize function in the `kornia` library, I found that the `__init__()` function has the parameter `return_transform: Optional[bool] = None`. However, I am not sure why it would raise this error.
Here is the complete error message:
`Traceback (most recent call last):`
 ` File "demo_single_pair.py", line 120, in <module>`
    `for batch_with_single_item in dataloader:`
  `File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__`
    `data = self._next_data()`
  `File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data`
    `data = self._dataset_fetcher.fetch(index)  # may raise StopIteration`
  `File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch`
    `data = [self.dataset[idx] for idx in possibly_batched_index]`
  `File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>`
    `data = [self.dataset[idx] for idx in possibly_batched_index]`
  `File "demo_single_pair.py", line 78, in __getitem__`
    `return self.marshal_getitem_data(item_data, self.split)`
  `File "/root/11/The-Change-You-Want-to-See/models/centernet_with_coam.py", line 254, in marshal_getitem_data`
    `) = utils.geometry.resize_image_and_annotations(`
  `File "/root/11/The-Change-You-Want-to-See/utils/geometry.py", line 134, in resize_image_and_annotations`
    `resize_augmentation = K.augmentation.Resize(output_shape_as_hw, return_transform=True)`
`TypeError: __init__() got an unexpected keyword argument 'return_transform'`
The model loading process is as follows:
`2023-09-03 15:12:27.477 | INFO     | models.centernet_with_coam:safely_load_state_dict:65 - Skip loading parameter: ``unet_model.decoder.blocks.0.conv1.0.weight, required shape: torch.Size([256, 3072, 3, 3]), loaded shape: torch.Size([256, 6144, 3, 3])`
`2023-09-03 15:12:27.478 | INFO     | models.centernet_with_coam:safely_load_state_dict:65 - Skip loading parameter:`
`unet_model.decoder.blocks.0.attention1.attention.cSE.1.weight, required shape: torch.Size([192, 3072, 1, 1]), loaded shape: `
`torch.Size([384, 6144, 1, 1])`
`2023-09-03 15:12:27.478 | INFO     | models.centernet_with_coam:safely_load_state_dict:65 - Skip loading parameter: `
`unet_model.decoder.blocks.0.attention1.attention.cSE.1.bias, required shape: torch.Size([192]), loaded shape: torch.Size([384])`
`2023-09-03 15:12:27.478 | INFO     | models.centernet_with_coam:safely_load_state_dict:65 - Skip loading parameter:`
`unet_model.decoder.blocks.0.attention1.attention.cSE.3.weight, required shape: torch.Size([3072, 192, 1, 1]), loaded shape: `
`torch.Size([6144, 384, 1, 1])`
`2023-09-03 15:12:27.478 | INFO     | models.centernet_with_coam:safely_load_state_dict:65 - Skip loading parameter: `
`unet_model.decoder.blocks.0.attention1.attention.cSE.3.bias, required shape: torch.Size([3072]), loaded shape: `
`torch.Size([6144])`
`2023-09-03 15:12:27.478 | INFO     | models.centernet_with_coam:safely_load_state_dict:65 - Skip loading parameter: `
`unet_model.decoder.blocks.0.attention1.attention.sSE.0.weight, required shape: torch.Size([1, 3072, 1, 1]), loaded shape: `
`torch.Size([1, 6144, 1, 1])`
`2023-09-03 15:12:27.478 | INFO     | models.centernet_with_coam:safely_load_state_dict:65 - Skip loading parameter: `
`unet_model.decoder.blocks.1.conv1.0.weight, required shape: torch.Size([256, 768, 3, 3]), loaded shape: torch.Size([256, 1280, 3, 3])`
`2023-09-03 15:12:27.478 | INFO     | models.centernet_with_coam:safely_load_state_dict:65 - Skip loading parameter: `
`unet_model.decoder.blocks.1.attention1.attention.cSE.1.weight, required shape: torch.Size([48, 768, 1, 1]), loaded shape: `
`torch.Size([80, 1280, 1, 1])`
`2023-09-03 15:12:27.479 | INFO     | models.centernet_with_coam:safely_load_state_dict:65 - Skip loading parameter: `
`unet_model.decoder.blocks.1.attention1.attention.cSE.1.bias, required shape: torch.Size([48]), loaded shape: torch.Size([80])`
`2023-09-03 15:12:27.479 | INFO     | models.centernet_with_coam:safely_load_state_dict:65 - Skip loading parameter: `
`unet_model.decoder.blocks.1.attention1.attention.cSE.3.weight, required shape: torch.Size([768, 48, 1, 1]), loaded shape:` `torch.Size([1280, 80, 1, 1])`
`2023-09-03 15:12:27.479 | INFO     | models.centernet_with_coam:safely_load_state_dict:65 - Skip loading parameter: `
`unet_model.decoder.blocks.1.attention1.attention.cSE.3.bias, required shape: torch.Size([768]), loaded shape: torch.Size([1280])`
`2023-09-03 15:12:27.479 | INFO     | models.centernet_with_coam:safely_load_state_dict:65 - Skip loading parameter: `
`unet_model.decoder.blocks.1.attention1.attention.sSE.0.weight, required shape: torch.Size([1, 768, 1, 1]), loaded shape: `
`torch.Size([1, 1280, 1, 1])`
Thank you for your attention.

**Comment by ragavsachdeva** [comment]
Hi, you should not be getting these "skip loading parameter" outputs. Are you using the correct config file (with the right num_coam_layers argument?). Did you install the packages correctly? Installing the wrong versions of the packages could explain the kornia issue too.

Please take a look at Option 2 under Installation instructions in the readme.

Particularly,

`pip install segmentation-models-pytorch@git+https://github.com/ragavsachdeva/segmentation_models.pytorch.git@0092ee4d6f851d89a4a401bb2dfa6187660b8dd3`

and

`pip install kornia@git+https://github.com/kornia/kornia@77589a58be6c603b7afd755d261783bd0c152a97`

**Comment by henuJackSon** [comment]
Hello Author,I followed your method to reinstall the `kornia` library and encountered a change in the error message. I tried running the command `python demo_single_pair.py --load_weights_from pretrained-resnet50-3x-coam-scSE-affine.ckpt --config_file configs/detection_resnet50_3x_coam_layers_affine.yml --decoder_attention scse` again. However, I encountered a new error and decided to install the library you mentioned last time: `pip install segmentation-models-pytorch@git+https://github.com/ragavsachdeva/segmentation_models.pytorch.git@0092ee4d6f851d89a4a401bb2dfa6187660b8dd3`. However, there was an error during the download process, which prompted a version issue. I am a bit confused about this error.
Here is the error message:
`Collecting segmentation-models-pytorch@ git+https://github.com/ragavsachdeva`
`/segmentation_models.pytorch.git@0092ee4d6f851d89a4a401bb2dfa6187660b8dd3`
  `Cloning https://github.com/ragavsachdeva/segmentation_models.pytorch.git (to revision `
`0092ee4d6f851d89a4a401bb2dfa6187660b8dd3) to /tmp/pip-install-ybb9_040/segmentation-models-`
`pytorch_354b990f9df6482fae5ee7ff0b72c64e`
 `Running command git clone -q https://github.com/ragavsachdeva/segmentation_models.pytorch.git /tmp/pip-install-ybb9_040`
`/segmentation-models-pytorch_354b990f9df6482fae5ee7ff0b72c64e`
`fatal: unable to access 'https://github.com/ragavsachdeva/segmentation_models.pytorch.git/': Failure when receiving data from `
`the peer`
`WARNING: Discarding git+https://github.com/ragavsachdeva`
`/segmentation_models.pytorch.git@0092ee4d6f851d89a4a401bb2dfa6187660b8dd3. Command errored out with exit status `
`128: git clone -q https://github.com/ragavsachdeva/segmentation_models.pytorch.git /tmp/pip-install-ybb9_040/segmentation-`
`models-pytorch_354b990f9df6482fae5ee7ff0b72c64e Check the logs for full command output.`
`ERROR: Could not find a version that satisfies the requirement segmentation-models-pytorch (unavailable) (from versions: 0.0.1, `
`0.0.2, 0.0.3, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.3.3)`
`ERROR: No matching distribution found for segmentation-models-pytorch (unavailable)`
Could you please provide guidance on how to resolve this issue?
Thank you for your attention.

**Comment by ragavsachdeva** [comment]
Hi, apologies for the delayed response. I will look into the installation process sometime this month and update it if it needs fixing. In the meanwhile, you may find our followup work helpful: https://github.com/ragavsachdeva/CYWS-3D. You can use the model for 2D images as well if you'd like and the demo script shows some examples.

**Comment by ragavsachdeva** [comment]
Hi, I just gave it a try and the following worked for me:

```
conda create -n cyws python=3.9
conda activate cyws
conda install -c pytorch pytorch=1.10.1 torchvision=0.11.2 cudatoolkit=11.3.1
pip install kornia@git+https://github.com/kornia/kornia@77589a58be6c603b7afd755d261783bd0c152a97
pip install matplotlib Shapely==1.8.0 easydict pytorch-lightning==1.5.8 loguru scipy h5py
python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/index.html
pip install mmcv-full==1.7.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10/index.html
pip install mmdet==2.28.2 wandb
pip install segmentation-models-pytorch@git+https://github.com/ragavsachdeva/segmentation_models.pytorch.git@0092ee4d6f851d89a4a401bb2dfa6187660b8dd3pi
pip install imageio==2.13.5
```

Can you please check if these installation instructions work for you?
