### ISSUE TITLE
Testing fails using the provided pre-trained model

### ISSUE THREAD

**Issue by gaobb** [ragavsachdeva/The-Change-You-Want-to-See#7]
Could you provide the MD5sum of the [pre-trained model ](https://thor.robots.ox.ac.uk/~vgg/data/cyws/pretrained-resnet50-3x-coam-scSE-affine.ckpt.gz)so that I can check if the downloaded model is correct?

Traceback (most recent call last):
  File "demo_single_pair.py", line 117, in <module>
    model = CenterNetWithCoAttention(configs)
  File "./The-Change-You-Want-to-See/models/centernet_with_coam.py", line 60, in __init__
    self.safely_load_state_dict(torch.load(args.load_weights_from)["state_dict"])
  File "/usr/local/python/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/python/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x1f'.

**Comment by ragavsachdeva** [comment]
Hi, apologies for the delayed response. Please see the [checksum file](https://thor.robots.ox.ac.uk/~vgg/data/cyws/SHA512SUMS) I've provided under datasets section. It also contains the checksum for the model checkpoint.

**Comment by duanwei99** [comment]
Hi, I also encountered this problem when following your work. I checked that the file is complete. Is it a problem with the pre-trained model?

**Comment by ragavsachdeva** [comment]
Hi, I can't test this right now so I'll get back to you but just to be sure, did you unzip the file properly?
`gzip -d pretrained-resnet50-3x-coam-scSE-affine.ckpt.gz`

**Comment by duanwei99** [comment]
Thank you very much for your reply. This problem occurred because I used the wrong version of segmentation_models.pytorch. After reporting the error, I commented out num_coam_layers, which caused this problem. I solved my problem by fully using the environment you provided.
