### ISSUE TITLE
Impainting Code

### ISSUE THREAD

**Issue by Chumsy0725** [ragavsachdeva/The-Change-You-Want-to-See#9]
Hello @ragavsachdeva, Thank you for your amazing work and it is quite interesting. 

I'm keen on the Impaining script you used in generating the COCO impainted dataset. Will you be able to release the dataset generation (impainting) scripts as well?

Thank you!

**Comment by ragavsachdeva** [comment]
Hi! I don't quite have the exact script anymore but I used [this model](https://github.com/advimman/lama). I am sure there are more recent inpainting models that you can use.
